version: '3.8'

services:
  backend:
    image: financiera_backend:latest  # <--- ESTO SOLUCIONA EL ERROR DEL FORMULARIO
    build: 
      context: /DATA/AppData/financiera-backend/FinancieraBackend
      dockerfile: Dockerfile
    container_name: financiera_backend
    restart: always
    ports:
      - "4323:4323"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - TZ=America/Lima
      - ASPNETCORE_URLS=http://+:4323
      - ConnectionStrings__MySqlConnection=Server=192.168.18.2;Port=3306;Database=db_financiera;User Id=admin_financiera;Password=admfinanciera;
      - DeepSeek__ApiKey=ollama
      - JwtSettings__Key=my_super_secret_key_12345_min_32_chars!!